[package]
name = "eigen-metrics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
eigen-metrics-derive.workspace = true
metrics.workspace = true

#prometheus
metrics-exporter-prometheus.workspace = true

eyre.workspace = true

#http
hyper.workspace = true


[dev-dependencies]
eigen-metrics-collectors-economic.workspace = true 
reqwest = "0.12.4"