[package]
name = "eigen-client-eth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
alloy-consensus.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-transport.workspace = true
alloy-json-rpc.workspace = true
alloy-node-bindings.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
async-trait.workspace = true
alloy-transport-http.workspace = true
eigen-logging.workspace = true
eigen-metrics-collectors-rpc-calls.workspace = true
once_cell.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true