[package]
name = "eigen-metrics-collectors-economic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
# reth.workspace = true
ethers.workspace = true
eigen-client-elcontracts.workspace = true
eigen-client-avsregistry.workspace = true
alloy-primitives.workspace = true
