[package]
name = "eigen-metrics-collectors-economic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
eigen-metrics-derive.workspace = true
metrics.workspace = true
eigen-logging.workspace = true