[package]
name = "eigen-services-blsaggregation"
description = "Eigen Layer SDK services blsaggregation"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
alloy-primitives.workspace = true
ark-bn254.workspace = true
ark-ec.workspace = true
eigen-crypto-bls.workspace = true
eigen-crypto-bn254.workspace = true
eigen-services-avsregistry.workspace = true
eigen-types.workspace = true
parking_lot.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
eigen-logging.workspace = true
sha2 = "0.10.8"
