[package]
name = "eigen-client-elcontracts"
description = "Eigen Layer core contracts sdk"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
eigen-types.workspace=true
thiserror.workspace = true
tracing.workspace = true

eigen-utils.workspace = true
alloy-primitives.workspace = true
