[package]
name = "eigen-client-elcontracts"
description = "Eigen Layer core contracts sdk"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
alloy-contract.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-types.workspace = true
eigen-logging.workspace = true
eigen-types.workspace = true
eigen-utils.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
alloy-eips.workspace = true
alloy-provider.workspace = true
alloy-signer-local.workspace = true
eigen-testing-utils.workspace = true
eigen-utils.workspace = true
once_cell.workspace = true
tokio.workspace = true
