[package]
name = "eigen-client-elcontracts"
description = "Eigen Layer core contracts sdk"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
ark-bn254 = "0.4.0"
ark-ff = "0.4.0"
eigen-types.workspace=true
thiserror.workspace = true
tracing.workspace = true

eigen-utils.workspace = true

alloy-sol-types.workspace = true
alloy-contract.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-signer.workspace = true
alloy-network.workspace = true
alloy-signer-wallet.workspace = true
reqwest.workspace = true


[dev-dependencies]
alloy-eips.workspace = true
eigen-testing-utils.workspace = true
tokio.workspace = true