[package]
name = "eigen-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
alloy-network.workspace = true
alloy-provider = {workspace = true , features = ["ws"]}
alloy-transport-http.workspace = true
reqwest.workspace = true
alloy-contract.workspace = true
alloy-signer-local.workspace = true
alloy-sol-types = { workspace = true, features = ["json"] }
alloy-pubsub.workspace = true
alloy-transport.workspace = true
alloy-json-rpc.workspace = true