[package]
name = "eigen-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
alloy-network.workspace = true
alloy-provider.workspace = true
alloy-transport-http.workspace = true
reqwest.workspace = true
alloy-sol-types.workspace = true
alloy-contract.workspace = true
alloy-signer-local.workspace = true